# Generated by Django 4.2.1 on 2023-05-20 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type_employeed',
            new_name='Type_employee',
        ),
    ]
