# Generated by Django 4.2.1 on 2023-05-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_rename_empleado_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type_employee',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='nombre_tipo'),
        ),
    ]
